# Generated by Django 4.0.3 on 2022-03-14 23:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ClienteNome', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Telefone', models.CharField(max_length=14)),
                ('EnderecoCompleto', models.CharField(max_length=200)),
                ('Profissao', models.CharField(max_length=50)),
                ('UploadDeCurriculo', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
